# Generated by Django 5.0.4 on 2024-04-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Breakfasttime', models.TimeField()),
                ('BreakfastLocation', models.CharField(max_length=30)),
                ('LunchTime', models.DateField()),
                ('LunchLocation', models.CharField(max_length=30)),
                ('DinnerTime', models.TimeField()),
                ('DinnerLocation', models.CharField(max_length=30)),
            ],
        ),
    ]
