# Generated by Django 5.0.4 on 2024-04-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanhealth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Starttime', models.TimeField()),
                ('Endtime', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='LunchTime',
            field=models.TimeField(),
        ),
    ]
