# Generated by Django 5.0.4 on 2024-04-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanhealth', '0002_sleep_alter_food_lunchtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Quantity', models.CharField(max_length=10)),
            ],
        ),
    ]
