# Generated by Django 5.0.4 on 2024-04-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanhealth', '0003_water'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Distance', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Walk',
            },
        ),
        migrations.RemoveField(
            model_name='water',
            name='Quantity',
        ),
    ]
