# Generated by Django 5.0.4 on 2024-04-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanhealth', '0004_walk_remove_water_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_food_location', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Hours', models.BigIntegerField()),
                ('Minitue', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Mobile',
            },
        ),
    ]
